Traceback (most recent call last):
  File "/home/mkato/mkato-jomon/0-0-quality_check/0-0-6-GT_histgram.py", line 63, in <module>
    plot_depth_and_mq_histograms(f'/home/mkato/hdd_data/data/0-0-raw_vcf/new_comp/{sample}.vcf.gz', f'{sample}.png')
  File "/home/mkato/mkato-jomon/0-0-quality_check/0-0-6-GT_histgram.py", line 14, in plot_depth_and_mq_histograms
    with gzip.open(vcf_file, 'rt') if vcf_file.endswith('.gz') else open(vcf_file, 'r') as file:
  File "/usr/lib/python3.10/gzip.py", line 58, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/usr/lib/python3.10/gzip.py", line 174, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/home/mkato/hdd_data/data/0-0-raw_vcf/new_comp/I14.vcf.gz'
